required: #you must create this folder and modify this value before running the script
  EZProxyLogFolderName: spu_logs #name of the SPU Log folder, must be in the ezp-stats program folder, I reccomend creating a symbolic link to the folder in the ezp-stats program folder

flags: #optional flags to turn features on and off
  UseResourceList: false #Use a list of domains to make the resource names prettier
  GenerateCharts: true #enable or disable charts in result pdf
  DoBranding: false #enable or disable branding in result pdf
  GeneratePDF: true #enable or disable the result pdf (only csv results)
  GenerateLog: true #enable or disable a logfile being generated
  UseLogins: false #Use proxy logins in stats (currently not implimented)

optional: #general values that you aren't required to change before use
  ResourceList: dblist.csv #name of your domain list .csv file see github for instructions on creating this.
  OutputFolderName: output #folder where results will output to, will be created on run
  LogFolderName: logs #folder where logs will output to, will be created on run

branding:
  OrgName: 'Public Library' #name of your organization, used in result PDF
  AccentColor: '#00bef2' #decorates the PDF with a chosen accent color
  BrandFolder: branding #folder where logos are fetched from
  BigLogo: biglogo.png #logo that is placed on the cover of the result pdf
  PageLogo: pagelogo.png #logo that is placed on each page of the result pdf

##########
#RESERVED#  -Not Ready Yet
##########

#pages: #pages to render in result pdf and their order
#- cover
#- resource_usage
#- user_stats
#- usage_times

#koha-sip2:
#  address: 127.0.0.1
#  username: null
#  password: null
