#########
#GENERAL#
#########

required:
  # You must modify the ezproxy_spulog_folder before first run!
  # Enter the location and name of the logfolder here, for example
  # if I am on windows, my username is 'ben' and my log folder is 
  # called "EZlogs" and is located in my documents folder, enter:
  # C:\User\ben\Documents\EZlogs
  # on the ezproxy_spulog_folder line.
  # ezp-stats.py MUST have read access to the folder to work.
  ezproxy_spulog_folder: spu_logs

# Optional flags to turn features on and off
flags: 
  do_debug_log: true #enable or disable a logfile being written
  
  # If true, appends new logs to existing file, 
  # If false, creates a new log file each run
  append_debug_log: true

# General values that you aren't required to change before use.
optional: 
  # Creates a name template to generate the name of the spu log file
  # Only edit this if the name of the spu log file has changed.
  # valid variables are $year and $month. the rest is a string value.
  spulog_name_scheme: spu$year$month.log

  # Folder path where results will output to. If it does not exist it 
  # will be created on run. ezp-stats.py MUST have read and write 
  # access to the folder to work.
  output_folder: output

  # Prefix before date of the output stat file.
  output_file_prefix: ezpstat

  # File where logs will output to, if it does not exist and
  # do_debug_log is true, it will be created on run of ezp-stats.py
  debug_log: ezp-stats


###############
#CSV VARIABLES#
###############

# do_user pulls the user field from the log file and uses it to
# calculate the number of unique users (in additon to IP users)
# and also if koha_sip2 integration is enabled, you can pull fields
# from those users for stats, like card type.
csv_flags:
  do_user: true # Use proxy logins in stats.
  do_extended_dates: true # Seprates date into date, weekday, & hour.
  do_resource_csv: true # Use a csv of URLs to match to SPU domains.
  do_spaced_categories: false # Use spaced names in CSV categories.
  do_koha_integration: false # Uses koha_sip2 to pull values from koha.

csv:
  # The path to your resource csv file. 
  # See github for instructions on creating this file.
  resource_csv: dblist.csv
  
  # Strips certain characters from the input string before it is passed
  # to the rest of the interpeter. by default it is used to strip
  # brackets from around the timestamp as it affects arrow formatting.
  strip_elements: '[]' # Currently not working TODO

  # Timestamp format given by the EZProxy SPU log. For a guide on how
  # to create this formatting, see this page:
  # https://arrow.readthedocs.io/en/latest/#supported-tokens
  timestamp_format: DD/MMM/YYYY:HH:mm:ss Z

#TODO - Write function that lets users re-arrange input and output columns via config.yml
csv_in:
  saddr: 0
  date: [1, 3] # Currently not working TODO
  usern: 3
  daddr: 5
  local: 6

# Creates a dictionary for CSV columns. The first value is the key,
# the second is the value i.E. (KEY: VALUE). Do not edit the names
# or the position of the keys.

# It is fine to change the values as they are used to name the columns
# in the output data and the PDF if enabled.
csv_out:
  date0: Date
  date1: Weekday
  date2: Hour
  usern: Username # Only used if do_user is true.
  saddr: Source Address
  daddr: Target Address
  local: Location


#koha_sip2:
#  address: 127.0.0.1
#  port: 22
#  insecure_login: false #enable to pull login details from yml file instead of credential file !NOT RECCOMENDED!
#  credential_file: null #secure credential file only the program has access to containing your koha sip2 username and password
#  username: null
#  password: null

################
#HTML VARIABLES#
################

html_flags:
  do_html: true # Enable or disable the result file. #TODO
  do_graphics: false # Enable or disable charts in result file #TODO

html_settings:
  title_prefix: Public Library Stats
  css_template: style.css
  resource_col:
    - Resource
    - Sessions
    - Unique Sessions
    - Library Sessions



###############
#PDF VARIABLES#
###############

pdf_flags:
  do_pdf: true # Enable or disable the result PDF.
  do_charts: true # Enable or disable charts in result PDF.
  do_branding: true # Enable or disable branding in result PDF.

pdf_pages:
  - cover

pdf_branding:
  # Name of your organization, used in result PDF file.
  org_name: Public Library

  pdf_title: SPU Log Stats

  title_font_file: SourceSansPro-Bold.ttf
  body_font_file: SourceSansPro-Regular.ttf

  # Decorates the PDF with a chosen accent colors in various places.
  # Choose 2 colors, 1st in the list is primary and 2nd is an accent
  # color. Colors are written in standard 6-digit color hex format.
  accent_color: 
    - '#00bef2'
    - '#2e2926'

  # Folder path where logos are fetched from. ezp-stats.py MUST have
  # read access to the folder to work properly. 
  brand_folder: branding 
  
  # Path to logo file that is placed on the cover of the result pdf. Only used
  # if cover page is in the page list. ezp-stats.py MUST have read access to
  # the file to work properly.
  #TODO - set image size limits and supported filetypes
  big_logo: big_logo.png
  
  # Path to logo file that is placed on each page of the result pdf.
  # ezp-stats.py MUST have read access to the file to work properly.
  #TODO - set image size limits and supported filetypes
  page_logo: page_logo.png
